name: Follett Project - WW2 Memorial Wall
favicon: null
layout_spectrum: 0.63478
typography_spectrum: 0.03253736044280231
title: WW2 Memorial Wall
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a09b95'
    - '#7d746b'
    - '#272519'
    - '#564e43'
    - '#c7c3c0'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
